import './globals.css'
import type { Metadata } from 'next'
import { Inter, Lato } from 'next/font/google'

import Navbar from '@components/Navbar'

const inter = Inter({ 
    subsets: ['latin'],
    variable: "--font-inter",
})

const lato = Lato({
    subsets: ['latin'],
    variable: "--font-lato",
    weight: '700'
})

export const metadata: Metadata = {
  title: 'Hiresh Bremanand | Developer',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={`${lato.variable} ${inter.variable} bg-gray-900`}>
            <Navbar />
            <form name="contact" data-netlify="true" netlify-honeypot="bot-field" hidden>
                <input type="text" name="name" />
                <input type="email" name="email" />
                <textarea name="message"></textarea>
            </form>
            {children}
        </body>
    </html>
  )
}
